use tree_sitter::Node;

use crate::yang::Token;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Statement {
    pub(crate) id: usize,
    pub keyword: Token,
    pub argument: Option<Token>,
}

impl TryFrom<&Node<'_>> for Statement {
    type Error = ();
    fn try_from(node: &Node<'_>) -> Result<Self, Self::Error> {
        let node_kind = node.kind();
        if node_kind.ends_with("_stmt") {
            let keyword_node = node.child(0).ok_or(())?;
            Ok(Statement {
                id: 0,
                keyword: Token::try_from(&keyword_node)?,
                argument: match node.child_by_field_name("arg") {
                    Some(argument_node) => Token::try_from(&argument_node).ok(),
                    None => None,
                },
            })
        } else {
            Err(())
        }
    }
}

// since statement_generated.rs is generated by build.rs,
// writing tests through which is not ideal and hard to maintain,
// so we put the tests for statement_generated.rs in this file instead
#[cfg(test)]
mod tests {
    use std::str::FromStr;
    use strum::IntoEnumIterator;

    use crate::yang::StatementKind;

    #[test]
    fn test_can_convert_statement_kind_from_string() {
        // test all the variants of StatementKind can be converted from their rule's string representations
        let rule_name_and_stmt_kind_tuple_vec = vec![
            ("action_stmt", StatementKind::Action),
            ("anydata_stmt", StatementKind::Anydata),
            ("anyxml_stmt", StatementKind::Anyxml),
            ("argument_stmt", StatementKind::Argument),
            ("augment_stmt", StatementKind::Augment),
            ("base_stmt", StatementKind::Base),
            ("belongs_to_stmt", StatementKind::BelongsTo),
            ("bit_stmt", StatementKind::Bit),
            ("case_stmt", StatementKind::Case),
            ("choice_stmt", StatementKind::Choice),
            ("config_stmt", StatementKind::Config),
            ("contact_stmt", StatementKind::Contact),
            ("container_stmt", StatementKind::Container),
            ("default_stmt", StatementKind::Default),
            ("description_stmt", StatementKind::Description),
            ("deviate_add_stmt", StatementKind::DeviateAdd),
            ("deviate_delete_stmt", StatementKind::DeviateDelete),
            (
                "deviate_not_supported_stmt",
                StatementKind::DeviateNotSupported,
            ),
            ("deviate_replace_stmt", StatementKind::DeviateReplace),
            ("deviation_stmt", StatementKind::Deviation),
            ("enum_stmt", StatementKind::Enum),
            ("error_app_tag_stmt", StatementKind::ErrorAppTag),
            ("error_message_stmt", StatementKind::ErrorMessage),
            ("extension_stmt", StatementKind::Extension),
            ("feature_stmt", StatementKind::Feature),
            ("fraction_digits_stmt", StatementKind::FractionDigits),
            ("grouping_stmt", StatementKind::Grouping),
            ("identity_stmt", StatementKind::Identity),
            ("if_feature_stmt", StatementKind::IfFeature),
            ("import_stmt", StatementKind::Import),
            ("include_stmt", StatementKind::Include),
            ("input_stmt", StatementKind::Input),
            ("key_stmt", StatementKind::Key),
            ("leaf_stmt", StatementKind::Leaf),
            ("leaf_list_stmt", StatementKind::LeafList),
            ("length_stmt", StatementKind::Length),
            ("list_stmt", StatementKind::List),
            ("mandatory_stmt", StatementKind::Mandatory),
            ("max_elements_stmt", StatementKind::MaxElements),
            ("min_elements_stmt", StatementKind::MinElements),
            ("modifier_stmt", StatementKind::Modifier),
            ("module_stmt", StatementKind::Module),
            ("must_stmt", StatementKind::Must),
            ("namespace_stmt", StatementKind::Namespace),
            ("notification_stmt", StatementKind::Notification),
            ("ordered_by_stmt", StatementKind::OrderedBy),
            ("organization_stmt", StatementKind::Organization),
            ("output_stmt", StatementKind::Output),
            ("path_stmt", StatementKind::Path),
            ("pattern_stmt", StatementKind::Pattern),
            ("position_stmt", StatementKind::Position),
            ("prefix_stmt", StatementKind::Prefix),
            ("presence_stmt", StatementKind::Presence),
            ("range_stmt", StatementKind::Range),
            ("reference_stmt", StatementKind::Reference),
            ("refine_stmt", StatementKind::Refine),
            ("require_instance_stmt", StatementKind::RequireInstance),
            ("revision_date_stmt", StatementKind::RevisionDate),
            ("revision_stmt", StatementKind::Revision),
            ("rpc_stmt", StatementKind::Rpc),
            ("status_stmt", StatementKind::Status),
            ("submodule_stmt", StatementKind::Submodule),
            ("typedef_stmt", StatementKind::Typedef),
            ("type_stmt", StatementKind::Type),
            ("unique_stmt", StatementKind::Unique),
            ("units_stmt", StatementKind::Units),
            ("unknown_stmt", StatementKind::Unknown),
            ("uses_augment_stmt", StatementKind::UsesAugment),
            ("uses_stmt", StatementKind::Uses),
            ("value_stmt", StatementKind::Value),
            ("when_stmt", StatementKind::When),
            ("yang_version_stmt", StatementKind::YangVersion),
            ("yin_element_stmt", StatementKind::YinElement),
        ];
        assert_eq!(
            rule_name_and_stmt_kind_tuple_vec.len(),
            StatementKind::iter().count()
        );
        for (rule_name, expected_stmt_kind) in rule_name_and_stmt_kind_tuple_vec {
            let stmt_kind = StatementKind::from_str(rule_name).unwrap();
            assert_eq!(stmt_kind, expected_stmt_kind);
        }
    }

    #[test]
    fn test_cannot_convert_statement_kind_from_string() {
        let stmt_kind_result = StatementKind::from_str("foo_stmt");
        assert!(stmt_kind_result.is_err());
    }

    #[test]
    fn test_can_convert_statement_kind_to_expected_string() {
        // test all the variants of StatementKind can be converted to their expected string representations
        // the expected string representations are defined in the #[strum(to_string = "...")] annotations in statement.rs
        // the expected string MUST not contains "_", and MUST not ends with "_stmt"
        let stmt_kind_and_expected_str_tuple_vec = vec![
            (StatementKind::Action, "action"),
            (StatementKind::Anydata, "anydata"),
            (StatementKind::Anyxml, "anyxml"),
            (StatementKind::Argument, "argument"),
            (StatementKind::Augment, "augment"),
            (StatementKind::Base, "base"),
            (StatementKind::BelongsTo, "belongs-to"),
            (StatementKind::Bit, "bit"),
            (StatementKind::Case, "case"),
            (StatementKind::Choice, "choice"),
            (StatementKind::Config, "config"),
            (StatementKind::Contact, "contact"),
            (StatementKind::Container, "container"),
            (StatementKind::Default, "default"),
            (StatementKind::Description, "description"),
            (StatementKind::DeviateAdd, "deviate-add"),
            (StatementKind::DeviateDelete, "deviate-delete"),
            (StatementKind::DeviateNotSupported, "deviate-not-supported"),
            (StatementKind::DeviateReplace, "deviate-replace"),
            (StatementKind::Deviation, "deviation"),
            (StatementKind::Enum, "enum"),
            (StatementKind::ErrorAppTag, "error-app-tag"),
            (StatementKind::ErrorMessage, "error-message"),
            (StatementKind::Extension, "extension"),
            (StatementKind::Feature, "feature"),
            (StatementKind::FractionDigits, "fraction-digits"),
            (StatementKind::Grouping, "grouping"),
            (StatementKind::Identity, "identity"),
            (StatementKind::IfFeature, "if-feature"),
            (StatementKind::Import, "import"),
            (StatementKind::Include, "include"),
            (StatementKind::Input, "input"),
            (StatementKind::Key, "key"),
            (StatementKind::Leaf, "leaf"),
            (StatementKind::LeafList, "leaf-list"),
            (StatementKind::Length, "length"),
            (StatementKind::List, "list"),
            (StatementKind::Mandatory, "mandatory"),
            (StatementKind::MaxElements, "max-elements"),
            (StatementKind::MinElements, "min-elements"),
            (StatementKind::Modifier, "modifier"),
            (StatementKind::Module, "module"),
            (StatementKind::Must, "must"),
            (StatementKind::Namespace, "namespace"),
            (StatementKind::Notification, "notification"),
            (StatementKind::OrderedBy, "ordered-by"),
            (StatementKind::Organization, "organization"),
            (StatementKind::Output, "output"),
            (StatementKind::Path, "path"),
            (StatementKind::Pattern, "pattern"),
            (StatementKind::Position, "position"),
            (StatementKind::Prefix, "prefix"),
            (StatementKind::Presence, "presence"),
            (StatementKind::Range, "range"),
            (StatementKind::Reference, "reference"),
            (StatementKind::Refine, "refine"),
            (StatementKind::RequireInstance, "require-instance"),
            (StatementKind::RevisionDate, "revision-date"),
            (StatementKind::Revision, "revision"),
            (StatementKind::Rpc, "rpc"),
            (StatementKind::Status, "status"),
            (StatementKind::Submodule, "submodule"),
            (StatementKind::Typedef, "typedef"),
            (StatementKind::Type, "type"),
            (StatementKind::Unique, "unique"),
            (StatementKind::Units, "units"),
            (StatementKind::Unknown, "unknown"),
            (StatementKind::UsesAugment, "uses-augment"),
            (StatementKind::Uses, "uses"),
            (StatementKind::Value, "value"),
            (StatementKind::When, "when"),
            (StatementKind::YangVersion, "yang-version"),
            (StatementKind::YinElement, "yin-element"),
        ];
        assert_eq!(
            stmt_kind_and_expected_str_tuple_vec.len(),
            StatementKind::iter().count()
        );
        for (stmt_kind, expected_str) in stmt_kind_and_expected_str_tuple_vec {
            let stmt_kind_str = stmt_kind.to_string();
            assert_eq!(stmt_kind_str, expected_str);
        }
    }
}
