/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_prefix = 4,
  anon_sym_SEMI = 5,
  anon_sym_submodule = 6,
  anon_sym_belongs_DASHto = 7,
  anon_sym_yang_DASHversion = 8,
  anon_sym_1 = 9,
  anon_sym_1_DOT1 = 10,
  anon_sym_SQUOTE = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_namespace = 13,
  sym_comment = 14,
  sym_identifier = 15,
  sym__rfc3986_uri = 16,
  sym_yang = 17,
  sym_module = 18,
  sym__module_block = 19,
  sym_prefix = 20,
  sym_submodule = 21,
  sym__submodule_block = 22,
  sym_belongs_to = 23,
  sym_yang_version = 24,
  sym__yang_versions = 25,
  sym__yang_version_arg_str = 26,
  sym_namespace = 27,
  sym__prefix_arg_str = 28,
  sym__identifier_arg_str = 29,
  aux_sym__module_block_repeat1 = 30,
  aux_sym__submodule_block_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_prefix] = "prefix",
  [anon_sym_SEMI] = ";",
  [anon_sym_submodule] = "submodule",
  [anon_sym_belongs_DASHto] = "belongs-to",
  [anon_sym_yang_DASHversion] = "yang-version",
  [anon_sym_1] = "1",
  [anon_sym_1_DOT1] = "1.1",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_namespace] = "namespace",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym__rfc3986_uri] = "uri_str",
  [sym_yang] = "yang",
  [sym_module] = "module",
  [sym__module_block] = "_module_block",
  [sym_prefix] = "prefix",
  [sym_submodule] = "submodule",
  [sym__submodule_block] = "_submodule_block",
  [sym_belongs_to] = "belongs_to",
  [sym_yang_version] = "yang_version",
  [sym__yang_versions] = "_yang_versions",
  [sym__yang_version_arg_str] = "_yang_version_arg_str",
  [sym_namespace] = "namespace",
  [sym__prefix_arg_str] = "_prefix_arg_str",
  [sym__identifier_arg_str] = "_identifier_arg_str",
  [aux_sym__module_block_repeat1] = "_module_block_repeat1",
  [aux_sym__submodule_block_repeat1] = "_submodule_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_prefix] = anon_sym_prefix,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_submodule] = anon_sym_submodule,
  [anon_sym_belongs_DASHto] = anon_sym_belongs_DASHto,
  [anon_sym_yang_DASHversion] = anon_sym_yang_DASHversion,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_1_DOT1] = anon_sym_1_DOT1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_namespace] = anon_sym_namespace,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym__rfc3986_uri] = sym__rfc3986_uri,
  [sym_yang] = sym_yang,
  [sym_module] = sym_module,
  [sym__module_block] = sym__module_block,
  [sym_prefix] = sym_prefix,
  [sym_submodule] = sym_submodule,
  [sym__submodule_block] = sym__submodule_block,
  [sym_belongs_to] = sym_belongs_to,
  [sym_yang_version] = sym_yang_version,
  [sym__yang_versions] = sym__yang_versions,
  [sym__yang_version_arg_str] = sym__yang_version_arg_str,
  [sym_namespace] = sym_namespace,
  [sym__prefix_arg_str] = sym__prefix_arg_str,
  [sym__identifier_arg_str] = sym__identifier_arg_str,
  [aux_sym__module_block_repeat1] = aux_sym__module_block_repeat1,
  [aux_sym__submodule_block_repeat1] = aux_sym__submodule_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prefix] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_submodule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_belongs_DASHto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yang_DASHversion] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1_DOT1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__rfc3986_uri] = {
    .visible = true,
    .named = true,
  },
  [sym_yang] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym__module_block] = {
    .visible = false,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_submodule] = {
    .visible = true,
    .named = true,
  },
  [sym__submodule_block] = {
    .visible = false,
    .named = true,
  },
  [sym_belongs_to] = {
    .visible = true,
    .named = true,
  },
  [sym_yang_version] = {
    .visible = true,
    .named = true,
  },
  [sym__yang_versions] = {
    .visible = false,
    .named = true,
  },
  [sym__yang_version_arg_str] = {
    .visible = false,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym__prefix_arg_str] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier_arg_str] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__module_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__submodule_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arg, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = sym__rfc3986_uri,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '"', 65,
        '\'', 64,
        '/', 3,
        '1', 62,
        ';', 58,
        'b', 16,
        'm', 36,
        'n', 9,
        'p', 42,
        's', 48,
        'y', 10,
        '{', 55,
        '}', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(69);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(65);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(51);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(47);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(49);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(6);
      END_STATE();
    case 25:
      if (lookahead == 'g') ADVANCE(46);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 51:
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 52:
      if (lookahead == 'x') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_prefix);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_submodule);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_belongs_DASHto);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_yang_DASHversion);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_1);
      if (lookahead == '.') ADVANCE(8);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_1_DOT1);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2, .external_lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_prefix] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_submodule] = ACTIONS(1),
    [anon_sym_belongs_DASHto] = ACTIONS(1),
    [anon_sym_yang_DASHversion] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [anon_sym_1_DOT1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__rfc3986_uri] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_yang] = STATE(33),
    [sym_module] = STATE(37),
    [sym_submodule] = STATE(37),
    [anon_sym_module] = ACTIONS(5),
    [anon_sym_submodule] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_prefix,
    ACTIONS(13), 1,
      anon_sym_yang_DASHversion,
    ACTIONS(15), 1,
      anon_sym_namespace,
    STATE(4), 4,
      sym_prefix,
      sym_yang_version,
      sym_namespace,
      aux_sym__module_block_repeat1,
  [22] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_prefix,
    ACTIONS(22), 1,
      anon_sym_yang_DASHversion,
    ACTIONS(25), 1,
      anon_sym_namespace,
    STATE(3), 4,
      sym_prefix,
      sym_yang_version,
      sym_namespace,
      aux_sym__module_block_repeat1,
  [44] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_prefix,
    ACTIONS(13), 1,
      anon_sym_yang_DASHversion,
    ACTIONS(15), 1,
      anon_sym_namespace,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    STATE(3), 4,
      sym_prefix,
      sym_yang_version,
      sym_namespace,
      aux_sym__module_block_repeat1,
  [66] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_yang_DASHversion,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    ACTIONS(32), 1,
      anon_sym_belongs_DASHto,
    STATE(8), 3,
      sym_belongs_to,
      sym_yang_version,
      aux_sym__submodule_block_repeat1,
  [84] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      anon_sym_1,
    ACTIONS(36), 1,
      anon_sym_1_DOT1,
    ACTIONS(38), 1,
      anon_sym_SQUOTE,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    STATE(26), 2,
      sym__yang_versions,
      sym__yang_version_arg_str,
  [104] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_belongs_DASHto,
    ACTIONS(47), 1,
      anon_sym_yang_DASHversion,
    STATE(7), 3,
      sym_belongs_to,
      sym_yang_version,
      aux_sym__submodule_block_repeat1,
  [122] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_yang_DASHversion,
    ACTIONS(32), 1,
      anon_sym_belongs_DASHto,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    STATE(7), 3,
      sym_belongs_to,
      sym_yang_version,
      aux_sym__submodule_block_repeat1,
  [140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 5,
      anon_sym_RBRACE,
      anon_sym_prefix,
      anon_sym_belongs_DASHto,
      anon_sym_yang_DASHversion,
      anon_sym_namespace,
  [151] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(38), 2,
      sym__prefix_arg_str,
      sym__identifier_arg_str,
  [165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 4,
      anon_sym_RBRACE,
      anon_sym_prefix,
      anon_sym_yang_DASHversion,
      anon_sym_namespace,
  [175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 4,
      anon_sym_RBRACE,
      anon_sym_prefix,
      anon_sym_yang_DASHversion,
      anon_sym_namespace,
  [185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(19), 1,
      sym__identifier_arg_str,
  [198] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(21), 1,
      sym__identifier_arg_str,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_1,
    ACTIONS(68), 1,
      anon_sym_1_DOT1,
    STATE(34), 1,
      sym__yang_versions,
  [224] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(30), 1,
      sym__identifier_arg_str,
  [237] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_1,
    ACTIONS(74), 1,
      anon_sym_1_DOT1,
    STATE(23), 1,
      sym__yang_versions,
  [250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 3,
      anon_sym_RBRACE,
      anon_sym_belongs_DASHto,
      anon_sym_yang_DASHversion,
  [259] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym__module_block,
  [269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_LBRACE,
      anon_sym_SEMI,
  [277] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym__submodule_block,
  [287] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      sym__rfc3986_uri,
      sym_identifier,
  [295] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
  [302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
  [309] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
  [316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_SEMI,
  [323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_SEMI,
  [330] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
  [337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym_identifier,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_SEMI,
  [351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
  [358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [365] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
  [372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_SQUOTE,
  [379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [393] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_SEMI,
  [407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 104,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 140,
  [SMALL_STATE(10)] = 151,
  [SMALL_STATE(11)] = 165,
  [SMALL_STATE(12)] = 175,
  [SMALL_STATE(13)] = 185,
  [SMALL_STATE(14)] = 198,
  [SMALL_STATE(15)] = 211,
  [SMALL_STATE(16)] = 224,
  [SMALL_STATE(17)] = 237,
  [SMALL_STATE(18)] = 250,
  [SMALL_STATE(19)] = 259,
  [SMALL_STATE(20)] = 269,
  [SMALL_STATE(21)] = 277,
  [SMALL_STATE(22)] = 287,
  [SMALL_STATE(23)] = 295,
  [SMALL_STATE(24)] = 302,
  [SMALL_STATE(25)] = 309,
  [SMALL_STATE(26)] = 316,
  [SMALL_STATE(27)] = 323,
  [SMALL_STATE(28)] = 330,
  [SMALL_STATE(29)] = 337,
  [SMALL_STATE(30)] = 344,
  [SMALL_STATE(31)] = 351,
  [SMALL_STATE(32)] = 358,
  [SMALL_STATE(33)] = 365,
  [SMALL_STATE(34)] = 372,
  [SMALL_STATE(35)] = 379,
  [SMALL_STATE(36)] = 386,
  [SMALL_STATE(37)] = 393,
  [SMALL_STATE(38)] = 400,
  [SMALL_STATE(39)] = 407,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__module_block_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__module_block_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__module_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__module_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__submodule_block_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__submodule_block_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__submodule_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_yang_version, 3, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 3, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 3, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_belongs_to, 3, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifier_arg_str, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__module_block, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__module_block, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__submodule_block, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 3, 0, 1),
  [106] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__submodule_block, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_submodule, 3, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_yang, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__yang_version_arg_str, 3, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__rfc3986_uri = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__rfc3986_uri] = sym__rfc3986_uri,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__rfc3986_uri] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_yang_external_scanner_create(void);
void tree_sitter_yang_external_scanner_destroy(void *);
bool tree_sitter_yang_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_yang_external_scanner_serialize(void *, char *);
void tree_sitter_yang_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_yang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_yang_external_scanner_create,
      tree_sitter_yang_external_scanner_destroy,
      tree_sitter_yang_external_scanner_scan,
      tree_sitter_yang_external_scanner_serialize,
      tree_sitter_yang_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
